export const markerData = {
  stages: [
    {
      position: [56.1199, 10.158893],
      title: "Main Stage",
      description: "Headliners and evening shows.",
      queueTime: "5 min",
      prepTime: "Starts 21:00",
    },
    {
      position: [56.122, 10.160603],
      title: "Sunset Stage",
      description: "Indie and acoustic sets.",
      queueTime: "3 min",
      prepTime: "Starts 18:30",
    },
    {
      position: [56.12285, 10.161303],
      title: "DJ Arena",
      description: "Late-night electronic music.",
      queueTime: "8 min",
      prepTime: "Starts 23:00",
    },
  ],
  drinks: [
    {
      position: [56.1218, 10.1587],
      title: "Blue Bar",
      description: "Cocktails and soft drinks.",
      queueTime: "10 min",
      prepTime: "10-15 min",
    },
    {
      position: [56.1216, 10.16],
      title: "Craft Beer Spot",
      description: "Local and international beers.",
      queueTime: "6 min",
      prepTime: "5-8 min",
    },
    {
      position: [56.1214, 10.1613],
      title: "Fresh Lemonade",
      description: "Homemade lemonades and iced tea.",
      queueTime: "4 min",
      prepTime: "3-5 min",
    },
    {
      position: [56.1204, 10.1593],
      title: "Coffee Corner",
      description: "Espresso, cappuccino and snacks.",
      queueTime: "7 min",
      prepTime: "4-6 min",
    },
    {
      position: [56.1211, 10.1615],
      title: "Water Station",
      description: "Free refill for your bottles.",
      queueTime: "2 min",
      prepTime: "Instant",
    },
  ],
  toilets: [
    {
      position: [56.1214, 10.1587],
      title: "Toilets A",
      description: "Closest to the main entrance.",
      queueTime: "6 min",
      prepTime: "Open now",
    },
    {
      position: [56.1225, 10.161303],
      title: "Toilets B",
      description: "Near Sunset Stage.",
      queueTime: "9 min",
      prepTime: "Open now",
    },
    {
      position: [56.1211, 10.16108],
      title: "Toilets C",
      description: "Accessible cabins available.",
      queueTime: "4 min",
      prepTime: "Open now",
    },
    {
      position: [56.1204, 10.16068],
      title: "Toilets D",
      description: "Quiet zone side.",
      queueTime: "3 min",
      prepTime: "Open now",
    },
    {
      position: [56.1204, 10.1598],
      title: "Toilets E",
      description: "Near food trucks.",
      queueTime: "11 min",
      prepTime: "Open now",
    },
  ],
};
